config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
    resources :comments
  end
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/landing_page'
  root 'simple_pages#index'
  post 'simple_pages/thank_you'
  post 'payments/create'
  get 'simple_pages/payment_thank_you'
  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeBerlin</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="nav">
      <div class="nav-header">
        <div class="nav-title">
          <%= link_to 'Bike Berlin', root_path, :class => "navbar-brand" %>
        </div>
      </div>
      <div class="nav-btn">
        <label for="nav-check">
          <span></span>
          <span></span>
          <span></span>
        </label>
      </div>
      <input type="checkbox" id="nav-check">
      <div class="nav-links ml-auto">
        <%= link_to 'Home', root_path, :class => "home" %>
        <%= link_to 'About', simple_pages_about_path %>
        <%= link_to 'Contact', simple_pages_contact_path %>
        <%= link_to 'Products', products_path %>
        <%= link_to 'New', new_product_path %>
        <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        <% end %>
      </div>
      <div class"form-inline ml-auto">
        <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
        <%= form.text_field :q, id: 'q', value: params[:q], :class => "search-field", :type => "search", :placeholder => "Search", :ariaLabel => "Search"  %>
        <%= form.submit 'Search', :class => "search" %>
        <% end %>
      </div>
    </div>

    <% if notice %>
      <p id="notice" class="notice alert alert-primary"><%= notice %></p>
    <% end %>


    <%= yield %>

    <footer class="container-fluid">
      &copy; 2018 Bike Berlin
    </footer>

  </body>
</html>